#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libhugetlbfs
Version  : 2.23
Release  : 78
URL      : file:///aot/build/clearlinux/packages/libhugetlbfs/libhugetlbfs-v2.23.tar.gz
Source0  : file:///aot/build/clearlinux/packages/libhugetlbfs/libhugetlbfs-v2.23.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: libhugetlbfs-bin = %{version}-%{release}
Requires: libhugetlbfs-data = %{version}-%{release}
Requires: libhugetlbfs-man = %{version}-%{release}
BuildRequires : binutils-dev
BuildRequires : binutils-extras
BuildRequires : bison
BuildRequires : dejagnu
BuildRequires : docbook-utils
BuildRequires : docbook-xml
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : expect
BuildRequires : flex
BuildRequires : gcc
BuildRequires : gcc-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-doc
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libs-math
BuildRequires : gcc-libstdc++32
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : gdb-dev
BuildRequires : git
BuildRequires : glibc-bin
BuildRequires : glibc-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-doc
BuildRequires : glibc-extras
BuildRequires : glibc-lib-avx2
BuildRequires : glibc-libc32
BuildRequires : glibc-locale
BuildRequires : glibc-nscd
BuildRequires : glibc-staticdev
BuildRequires : glibc-utils
BuildRequires : gmp-dev
BuildRequires : gmp-staticdev
BuildRequires : graphviz
BuildRequires : guile
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libgcc1
BuildRequires : libstdc++
BuildRequires : libunwind
BuildRequires : libunwind-dev
BuildRequires : lz4-dev
BuildRequires : lz4-dev32
BuildRequires : lz4-staticdev
BuildRequires : nasm
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(zlib)
BuildRequires : xz-dev
BuildRequires : xz-dev32
BuildRequires : xz-staticdev
BuildRequires : yasm
BuildRequires : zlib-dev
BuildRequires : zlib-dev32
BuildRequires : zlib-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: libhugetlbfs-2.23-uncompressed-man-pages.patch

%description
03 December 2015 -- Yet another mailing list move
librelist seems to be dead or at least broken.  I have recieved several
emails directly saying that patches were posted, but they never got
responses and the archives always seem empty.  So we are moving the list
again.  This from here on out we will be using

%package bin
Summary: bin components for the libhugetlbfs package.
Group: Binaries
Requires: libhugetlbfs-data = %{version}-%{release}

%description bin
bin components for the libhugetlbfs package.


%package data
Summary: data components for the libhugetlbfs package.
Group: Data

%description data
data components for the libhugetlbfs package.


%package dev
Summary: dev components for the libhugetlbfs package.
Group: Development
Requires: libhugetlbfs-bin = %{version}-%{release}
Requires: libhugetlbfs-data = %{version}-%{release}
Provides: libhugetlbfs-devel = %{version}-%{release}
Requires: libhugetlbfs = %{version}-%{release}

%description dev
dev components for the libhugetlbfs package.


%package man
Summary: man components for the libhugetlbfs package.
Group: Default

%description man
man components for the libhugetlbfs package.


%package staticdev
Summary: staticdev components for the libhugetlbfs package.
Group: Default
Requires: libhugetlbfs-dev = %{version}-%{release}

%description staticdev
staticdev components for the libhugetlbfs package.


%prep
%setup -q -n libhugetlbfs
cd %{_builddir}/libhugetlbfs
%patch1 -p1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1624163187
export GCC_IGNORE_WERROR=1
## altflags1 content
export CFLAGS="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fPIC -Wl,-z,max-page-size=0x1000 -fvisibility=hidden -flto-partition=none
# gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common -funroll-loops
export CXXFLAGS="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export FCFLAGS="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
export FFLAGS="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -Wl,--build-id=sha1"
export CFFLAGS="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export LDFLAGS="-Ofast --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread -ldl -Wl,--build-id=sha1"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
## altflags1 end
## make_prepend content
echo 2.23 > version
## make_prepend end
make  %{?_smp_mflags}   BUILDTYPE=NATIVEONLY PREFIX=%{_prefix} LIBDIR64=/usr/lib64 LIBDIR32=/usr/lib32 CC32="gcc -m32" ELF32=elf_i386 V=1 VERBOSE=1


%install
export SOURCE_DATE_EPOCH=1624163187
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/hugeadm
/usr/bin/hugectl
/usr/bin/hugeedit
/usr/bin/pagesize

%files data
%defattr(-,root,root,-)
/usr/share/libhugetlbfs/ld
/usr/share/libhugetlbfs/ld.hugetlbfs
/usr/share/libhugetlbfs/ldscripts/elf32ppclinux.xB
/usr/share/libhugetlbfs/ldscripts/elf32ppclinux.xBDT
/usr/share/libhugetlbfs/ldscripts/elf64ppc.xB
/usr/share/libhugetlbfs/ldscripts/elf64ppc.xBDT
/usr/share/libhugetlbfs/ldscripts/elf_i386.xB
/usr/share/libhugetlbfs/ldscripts/elf_i386.xBDT
/usr/share/libhugetlbfs/ldscripts/elf_x86_64.xB
/usr/share/libhugetlbfs/ldscripts/elf_x86_64.xBDT

%files dev
%defattr(-,root,root,-)
/usr/include/hugetlbfs.h
/usr/lib/libhugetlbfs.so
/usr/lib/libhugetlbfs_privutils.so
/usr/lib64/libhugetlbfs.so
/usr/lib64/libhugetlbfs_privutils.so

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ld.hugetlbfs.1
/usr/share/man/man1/pagesize.1
/usr/share/man/man3/free_huge_pages.3
/usr/share/man/man3/free_hugepage_region.3
/usr/share/man/man3/get_huge_pages.3
/usr/share/man/man3/get_hugepage_region.3
/usr/share/man/man3/gethugepagesize.3
/usr/share/man/man3/gethugepagesizes.3
/usr/share/man/man3/getpagesizes.3
/usr/share/man/man3/hugetlbfs_find_path.3
/usr/share/man/man3/hugetlbfs_find_path_for_size.3
/usr/share/man/man3/hugetlbfs_test_path.3
/usr/share/man/man3/hugetlbfs_unlinked_fd.3
/usr/share/man/man3/hugetlbfs_unlinked_fd_for_size.3
/usr/share/man/man7/libhugetlbfs.7
/usr/share/man/man8/hugeadm.8
/usr/share/man/man8/hugectl.8
/usr/share/man/man8/hugeedit.8

%files staticdev
%defattr(-,root,root,-)
/usr/lib/libhugetlbfs.a
/usr/lib64/libhugetlbfs.a
